version: '3'
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: starter
    ports:
      - "5432:5432"
    volumes:
      - ~/docker-volumes/postgresql:/var/lib/postgresql/data